name: docker-build
on: 
  schedule:
    - cron: '18 7 2,12,22 * *'
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - run: |
          mkdir -p ~/.docker
          echo '{"experimental": "enabled"}' > ~/.docker/config.json
          sudo docker run --rm --privileged multiarch/qemu-user-static --reset --persistent yes --credential yes

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
      - run: 'gcloud --quiet auth configure-docker'

      - name: login-dockerhub
        run: "echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u sorah --password-stdin"

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 14400
      - name: Login to ECR Public
        run: 'aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws'
        # FIXME: https://github.com/aws-actions/amazon-ecr-login/issues/116
        # uses: aws-actions/amazon-ecr-login@v1

      - uses: actions/checkout@master

      - run: "ruby build.rb --push --pull"
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

      - run: "ruby push.rb"
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
