name: docker-build
on: 
  schedule:
    - cron: '18 7 2,12,22 * *'
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-ruby@master
        with:
          ruby-version: '2.7'
      - uses: actions/checkout@master
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
      - run: 'gcloud --quiet auth configure-docker'
      - name: login-dockerhub
        run: "echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u sorah --password-stdin"
      - run: "ruby build.rb --push"
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
